import { describe, it, expect } from 'vitest'
import { cleanPrompt, summarize } from './claudeSummary'

const userLine = (text: string): string => JSON.stringify({ type: 'user', message: { role: 'user', content: text } })

describe('cleanPrompt', () => {
  it('strips slash-command caveat wrappers', () => {
    const raw = '<local-command-caveat>Caveat: generated by local commands.</local-command-caveat><command-name>/clear</command-name>real ask here'
    expect(cleanPrompt(raw)).toBe('real ask here')
  })

  it('strips system reminders', () => {
    expect(cleanPrompt('<system-reminder>memory dump</system-reminder> fix the bug')).toBe('fix the bug')
  })

  it('strips an unterminated wrapper rather than treating the tag as content', () => {
    expect(cleanPrompt('<local-command-caveat>Caveat: the messages below were')).toBe('')
  })

  it('collapses whitespace', () => {
    expect(cleanPrompt('a\n\n  b')).toBe('a b')
  })
})

describe('summarize', () => {
  it("prefers claude's own summary line wherever it appears", () => {
    const lines = [userLine('first prompt'), JSON.stringify({ type: 'summary', summary: 'Fix the daemon freeze' })]
    expect(summarize(lines)).toBe('Fix the daemon freeze')
  })

  it('falls back to the first real user prompt when there is no summary', () => {
    const lines = [
      JSON.stringify({ type: 'mode', mode: 'normal' }),
      userLine('<system-reminder>ignore me</system-reminder>'),
      userLine('Add a session cleanup view'),
    ]
    expect(summarize(lines)).toBe('Add a session cleanup view')
  })

  it('reads array-shaped content', () => {
    const lines = [JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'hello there' }] } })]
    expect(summarize(lines)).toBe('hello there')
  })

  it('skips unparseable lines (a live transcript can end mid-write)', () => {
    expect(summarize(['{"type":"user", broken', userLine('still found')])).toBe('still found')
  })

  it('truncates with an ellipsis', () => {
    expect(summarize([userLine('x'.repeat(200))], 10)).toBe('xxxxxxxxx…')
  })

  it('returns empty when nothing usable is present', () => {
    expect(summarize([JSON.stringify({ type: 'assistant' })])).toBe('')
  })
})
